name: Daily Stock Scan

on:
  schedule:
    # 設定排程時間 (UTC 時間)
    # 台灣時間 06:00 = UTC 22:00 (前一天)
    # 格式: 分 時 日 月 週
    - cron: '0 22 * * *'
  
  # 允許手動觸發 (方便測試)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas yfinance requests

    - name: Run Scan Script
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python daily_report.py