name: Daily Stock Scan & Sheet Sync

on:
  schedule:
    # 說明：GitHub 使用 UTC 時間
    # UTC 10:45 = 台灣時間 18:45 (週一至週五)
    - cron: '45 10 * * 1-5'
    
  workflow_dispatch: # 保留手動執行按鈕

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run Analysis and Report
      run: |
        echo "=== 開始安裝套件 ==="
        pip install pandas numpy yfinance matplotlib
        
        echo "=== 檢查安裝清單 ==="
        pip list | grep matplotlib
        
        echo "=== 執行 Python 程式 ==="
        python daily_report.py
        
    - name: Run Daily Report
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_SENDER }}
      run: |
        python daily_report.py





