name: Daily Stock Scan & Sheet Sync

on:
  schedule:
    # 說明：GitHub 使用 UTC 時間
    # UTC 10:45 = 台灣時間 18:45 (週一至週五)
    - cron: '45 10 * * 1-5'
    
  workflow_dispatch: # 保留手動執行按鈕

jobs:
  build:
    runs-on: ubuntu-latest

steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies and Run Report
      run: |
        echo "Step 1: Upgrading pip..."
        python -m pip install --upgrade pip
          
        echo "Step 2: Installing libraries..."
        pip install pandas numpy yfinance matplotlib
          
        echo "Step 3: Verifying installation..."
        pip list | grep matplotlib
          
        echo "Step 4: Running Python script..."
        python daily_report.py
        
    - name: Run Daily Report
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_SENDER }}
      run: |
        python daily_report.py








