name: AI Daily Scan & Report

on:
  schedule:
    - cron: '15 10 * * 1-5' # 18:35 (避開尖峰，通常會準時觸發)
  workflow_dispatch: # 允許手動按按鈕執行測試

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy
        
    - name: Run Scan Script
      env:
        # 從 GitHub Secrets 讀取密碼
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_SENDER }} # 預設寄給自己，也可另設 Secret
      run: |
        python daily_report.py

