import os
import json
import time
import requests
import pandas as pd
import yfinance as yf
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from concurrent.futures import ThreadPoolExecutor

# 1. 讀取環境變數 (GitHub Secrets)
# 注意：這裡改用 os.environ，因為不是在 Streamlit 環境下執行
EMAIL_SENDER = os.environ.get("EMAIL_SENDER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
EMAIL_RECEIVER = os.environ.get("EMAIL_RECEIVER", EMAIL_SENDER)

# 2. 載入資料庫
# 確保 sector_db.json 和 stock_names.json 都在同一目錄下
try:
    with open("sector_db.json", "r", encoding="utf-8") as f:
        SECTOR_DB = json.load(f)
    with open("stock_names.json", "r", encoding="utf-8") as f:
        STOCK_NAMES = json.load(f)
except:
    print("❌ 資料庫讀取失敗")
    SECTOR_DB = {}
    STOCK_NAMES = {}

# 3. 核心運算函數 (精簡版)
def get_stock_data(ticker):
    try:
        if ticker.isdigit(): ticker = f"{ticker}.TW"
        df = yf.Ticker(ticker).history(period="1y")
        if df.empty: return pd.DataFrame()
        return df
    except: return pd.DataFrame()

def calculate_score(ticker):
    try:
        df = get_stock_data(ticker)
        if df.empty or len(df) < 60: return None
        
        # 簡單計算指標 (與主程式邏輯一致)
        close = df['Close']
        ma20 = close.rolling(20).mean()
        ma60 = close.rolling(60).mean()
        vol = df['Volume']
        vol_ma20 = vol.rolling(20).mean()
        
        last = df.iloc[-1]
        score = 0
        
        # 技術
        if last['Close'] > ma20.iloc[-1]: score += 2
        if ma60.iloc[-1] > ma60.iloc[-2]: score += 3 # 斜率向上
        if last['Close'] > ma60.iloc[-1]: score += 1
        
        # 籌碼與動能
        if last['Volume'] > vol_ma20.iloc[-1]: score += 3
        if (last['Close'] - df.iloc[-2]['Close']) > 0: score += 3
        
        return {
            "代號": ticker,
            "名稱": STOCK_NAMES.get(ticker, ticker),
            "總分": score,
            "現價": last['Close']
        }
    except: return None

def send_email(subject, html_content):
    if not EMAIL_SENDER or not EMAIL_PASSWORD:
        print("❌ 未設定 Email Secrets")
        return

    msg = MIMEMultipart()
    msg['From'] = f"AI 戰情室 <{EMAIL_SENDER}>"
    msg['To'] = EMAIL_RECEIVER
    msg['Subject'] = subject
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())
        server.quit()
        print("✅ 郵件發送成功")
    except Exception as e:
        print(f"❌ 發送失敗: {e}")

# 4. 主執行程序
def main():
    print("🚀 開始執行每日晨間掃描...")
    
    # 收集所有股票
    all_tickers = set()
    for sub in SECTOR_DB.values():
        for t_list in sub.values():
            for t in t_list: all_tickers.add(t)
    
    target_list = list(all_tickers)
    print(f"📡 目標數量: {len(target_list)} 檔")

    results = []
    # GitHub Runner 效能較強，可以用 10 執行緒
    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = list(executor.map(calculate_score, target_list))
        
    for res in futures:
        if res: results.append(res)
        
    if not results:
        print("❌ 無掃描結果")
        return

    # 排序與選出 Top 10
    res_df = pd.DataFrame(results).sort_values("總分", ascending=False)
    top_stock = res_df.iloc[0]
    
    # 生成 HTML (Top 10)
    top_10_html = ""
    for i in range(min(10, len(res_df))):
        row = res_df.iloc[i]
        icon = "🔹"
        if i == 0: icon = "🥇"
        elif i == 1: icon = "🥈"
        elif i == 2: icon = "🥉"
        top_10_html += f"<li>{icon} <b>{row['名稱']}</b> ({row['代號']}) - 總分: {row['總分']} | 現價: {row['現價']:.1f}</li>"

    email_html = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #00adb5;">🤖 AI 戰情室晨報 (自動排程)</h2>
        <hr>
        <p>GitHub Actions 自動執行掃描完畢，Top 10 強勢股如下：</p>
        <ul style="line-height: 1.6;">{top_10_html}</ul>
        <br>
        <p style="color: gray;">Generated by GitHub Actions at 06:00 CST</p>
    </body>
    </html>
    """
    
    subject = f"【AI晨報】冠軍: {top_stock['名稱']} (總分:{top_stock['總分']})"
    send_email(subject, email_html)

if __name__ == "__main__":
    main()