name: AI Daily Scan & Report

on:
  schedule:
    # UTC 10:00 = 台灣時間 18:00 (週一至週五)
    - cron: '0 10 * * 1-5'
  workflow_dispatch: # 允許手動按按鈕執行測試

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy
        
    - name: Run Scan Script
      env:
        # 從 GitHub Secrets 讀取密碼
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_SENDER }} # 預設寄給自己，也可另設 Secret
      run: |
        python daily_report.py
